services:

  # CONFIG SERVER
  ms-config:
    build: ./backend/ms-config
    container_name: ms-config
    ports:
      - "8888:8888"
    networks:
      - microservices-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
 
  # DISCOVERY SERVER (Eureka)
  ms-discover:
    build: ./backend/ms-discover
    container_name: ms-discover
    ports:
      - "8761:8761"
    networks:
      - microservices-net
    depends_on:
      ms-config:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
 
  # API GATEWAY
  ms-gateway:
    build: ./backend/ms-gateway
    container_name: ms-gateway
    ports:
      - "8088:8088"
    networks:
      - microservices-net
    depends_on:
      ms-config:
        condition: service_healthy
      ms-discover:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MS-USER Database
  ms-user-db:
    image: mariadb:11
    container_name: ms-user-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_user
      MYSQL_USER: user
      MYSQL_PASSWORD: passer123
    ports:
      - "3306:3306"
    networks:
      - microservices-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 30s  # Augmenter le timeout
      retries: 20
      start_period: 60s
    command: 
      - --wait-timeout=28800
      - --interactive-timeout=28800


  # MS-USER
  ms-user:
    build: ./backend/ms-user
    container_name: ms-user
    ports:
      - "8081:8081"
    networks:
      - microservices-net
    depends_on:
      ms-config:
        condition: service_healthy
      ms-discover:
        condition: service_healthy
      ms-user-db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # FRONTEND REACT + VITE 
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"         # NGINX sert lâ€™app sur 80
    networks:
      - microservices-net
    depends_on:
      ms-gateway:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5



  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: ms-user-db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - microservices-net
    depends_on:
      - ms-user-db
    restart: unless-stopped


networks:
  microservices-net:
    driver: bridge
