server:
  port: 8082

spring:
  application:
    name: ms-cv
  config:
    import: "configserver:http://ms-config:8888"

eureka:
  client:
    service-url:
      defaultZone: http://ms-discover:8761/eureka

springdoc:
  api-docs:
    path: /ms-cv/api-docs 
    enabled: true
  swagger-ui:
    path: /ms-cv/swagger-ui.html
    enabled: true
